name: Bug Report
description: "Create a report to help us improve."
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: Description of the problem
      placeholder: Your problem description
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of go-shutdown
      value: "version of go-shutdown"
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: A minimal reproducible example or link to a public repository
      description: if your problem is related to a private repository, a minimal reproducible example is required.
      value: |-
        <details>

        ```go
        // add your code here
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      options:
        - label: Yes, I've included all information above (version, config, etc.).
          required: true
